/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ReviewsRouteImport } from './routes/reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/payouts': typeof PayoutsRoute
  '/promotions': typeof PromotionsRoute
  '/revenue': typeof RevenueRoute
  '/reviews': typeof ReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/payouts': typeof PayoutsRoute
  '/promotions': typeof PromotionsRoute
  '/revenue': typeof RevenueRoute
  '/reviews': typeof ReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/payouts': typeof PayoutsRoute
  '/promotions': typeof PromotionsRoute
  '/revenue': typeof RevenueRoute
  '/reviews': typeof ReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu'
    | '/orders'
    | '/payouts'
    | '/promotions'
    | '/revenue'
    | '/reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu'
    | '/orders'
    | '/payouts'
    | '/promotions'
    | '/revenue'
    | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/menu'
    | '/orders'
    | '/payouts'
    | '/promotions'
    | '/revenue'
    | '/reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  PayoutsRoute: typeof PayoutsRoute
  PromotionsRoute: typeof PromotionsRoute
  RevenueRoute: typeof RevenueRoute
  ReviewsRoute: typeof ReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  PayoutsRoute: PayoutsRoute,
  PromotionsRoute: PromotionsRoute,
  RevenueRoute: RevenueRoute,
  ReviewsRoute: ReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
